### ISSUE TITLE
Place an order

### ISSUE THREAD

**Issue by copypastedeveloper** [Still-Not-Quite-Human-Matrix/Orientation-Api#5]
As a customer, I'd like to be able to talk to a sales rep and have them place an order, so that I can buy cool new things.

Orders should be associated with a customer

**Comment by lewiskg** [comment]
Discussed with Nathan what the end point of this card should be.  Should be able to do two things:
1) Get from the db the orderId and associated customerId for that order;
When an attribute is placed:
2) Update a boolean attribute on the orders tables that states that an order has been "purchased."
